// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type LoginReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LogingRes struct {
	Token string `json:"token"`
}

type RegisterReq struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Gender   int16  `json:"gender"`
}

type GetDetailsRes struct {
	UserName string `json:"userName"`
}

type GetContentReq struct {
	Page     int `form:"page"`
	PageSize int `form:"pageSize"`
}

type GetContentRespItem struct {
	Id      string `json:"id"`
	UserId  string `json:"userId"`
	Content string `json:"content"`
	Title   string `json:"title"`
	View    int64  `json:"view"`
	Like    int64  `json:"like"`
}

type GetContentResp struct {
	Items []GetContentRespItem `json:"items"`
	Total int64                `json:"total"`
}

type AddContentReq struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Authorization string `header:"authorization, optional"`
}
